import { MusicTrack } from '../types';

export const SAMPLE_LIBRARY_TRACKS: MusicTrack[] = [
  {
    id: 'lib-2',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    duration: 200,
    durationFormatted: '03:20',
    releaseYear: '2020',
    genre: 'Synthwave / Pop',
    platform: 'youtube',
    originalUrl: 'https://music.youtube.com/watch?v=4NRXx6U8ABQ',
    coverUrl: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&auto=format&fit=crop&q=80',
    streamUrl: '/api/stream?title=The%20Weeknd%20-%20Blinding%20Lights',
    bitrate: '320 kbps',
    format: 'mp3',
    fileSizeMb: 8.2,
    bpm: 171,
    key: 'F# Minor',
    isDownloaded: true,
    isFavorite: true,
    addedAt: '2026-07-27T14:22:00Z',
    downloadedAt: '2026-07-27T14:22:15Z',
    filePath: 'Music/The Weeknd - Blinding Lights.mp3',
    lyrics: `I've been tryna call\nI've been on my own for long enough\nMaybe you can show me how to love, maybe\nI'm drowning in the night`,
    crossLinks: {
      spotify: 'https://open.spotify.com/track/0VjIj3ChA383mR239A1uR2',
      soundcloud: 'https://soundcloud.com/theweeknd/blinding-lights',
      youtube: 'https://music.youtube.com/watch?v=4NRXx6U8ABQ',
    },
  },
  {
    id: 'lib-3',
    title: 'Starboy',
    artist: 'The Weeknd',
    album: 'Starboy',
    duration: 230,
    durationFormatted: '03:50',
    releaseYear: '2016',
    genre: 'R&B / Electro-Pop',
    platform: 'spotify',
    originalUrl: 'https://open.spotify.com/track/7MX20X3E8S2bM262G04rM',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    streamUrl: '/api/stream?title=The%20Weeknd%20-%20Starboy',
    bitrate: '320 kbps',
    format: 'flac',
    fileSizeMb: 14.5,
    bpm: 186,
    key: 'G Major',
    isDownloaded: true,
    isFavorite: false,
    addedAt: '2026-07-26T18:05:00Z',
    downloadedAt: '2026-07-26T18:05:20Z',
    filePath: 'Music/The Weeknd - Starboy.flac',
    lyrics: `I'm tryna put you in the worst mood, ah\nP1 cleaner than your church shoes, ah\nManiac matter fact, blue asshole\n100k for a table, all in cash`,
    crossLinks: {
      spotify: 'https://open.spotify.com/track/7MX20X3E8S2bM262G04rM',
      youtube: 'https://music.youtube.com/watch?v=34Na4j8AVgA',
    },
  },
  {
    id: 'lib-4',
    title: 'Levitating',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    duration: 203,
    durationFormatted: '03:23',
    releaseYear: '2020',
    genre: 'Disco Pop',
    platform: 'spotify',
    originalUrl: 'https://open.spotify.com/track/4632P15A23G0M118R2',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    streamUrl: '/api/stream?title=Dua%20Lipa%20-%20Levitating',
    bitrate: '320 kbps',
    format: 'mp3',
    fileSizeMb: 7.9,
    bpm: 103,
    key: 'B Minor',
    isDownloaded: true,
    isFavorite: true,
    addedAt: '2026-07-25T11:15:00Z',
    downloadedAt: '2026-07-25T11:15:10Z',
    filePath: 'Music/Dua Lipa - Levitating.mp3',
    lyrics: `If you wanna run away with me, I know a galaxy\nAnd I can take you for a ride\nI had a premonition that we fell into a rhythm\nWhere the music don't stop for life`,
    crossLinks: {
      spotify: 'https://open.spotify.com/track/4632P15A23G0M118R2',
      soundcloud: 'https://soundcloud.com/dualipa/levitating',
    },
  },
  {
    id: 'lib-5',
    title: 'Get Lucky',
    artist: 'Daft Punk',
    album: 'Random Access Memories',
    duration: 248,
    durationFormatted: '04:08',
    releaseYear: '2013',
    genre: 'Funk / Electronic',
    platform: 'soundcloud',
    originalUrl: 'https://soundcloud.com/daftpunk/get-lucky',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    streamUrl: '/api/stream?title=Daft%20Punk%20-%20Get%20Lucky',
    bitrate: '320 kbps',
    format: 'wav',
    fileSizeMb: 24.2,
    bpm: 116,
    key: 'F# Minor',
    isDownloaded: true,
    isFavorite: false,
    addedAt: '2026-07-24T09:30:00Z',
    downloadedAt: '2026-07-24T09:30:40Z',
    filePath: 'Music/Daft Punk - Get Lucky.wav',
    lyrics: `Like the legend of the phoenix\nAll ends with beginnings\nWhat keeps the planet spinning\nThe force from the beginning`,
    crossLinks: {
      spotify: 'https://open.spotify.com/track/69kToP123m1G',
      soundcloud: 'https://soundcloud.com/daftpunk/get-lucky',
      youtube: 'https://music.youtube.com/watch?v=5NV6Rdv1a3I',
    },
  },
  {
    id: 'lib-6',
    title: 'Montero (Call Me By Your Name)',
    artist: 'Lil Nas X',
    album: 'MONTERO',
    duration: 137,
    durationFormatted: '02:17',
    releaseYear: '2021',
    genre: 'Hip-Hop / Pop',
    platform: 'youtube',
    originalUrl: 'https://music.youtube.com/watch?v=6zw9v12mG8Y',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
    streamUrl: '/api/stream?title=Lil%20Nas%20X%20-%20Montero',
    bitrate: '256 kbps',
    format: 'm4a',
    fileSizeMb: 5.2,
    bpm: 178,
    key: 'G# Minor',
    isDownloaded: true,
    isFavorite: true,
    addedAt: '2026-07-23T16:40:00Z',
    downloadedAt: '2026-07-23T16:40:08Z',
    filePath: 'Music/Lil Nas X - Montero (Call Me By Your Name).m4a',
    lyrics: `I caught it bad just the other day\nYou told me I'm the only one that you let touch it\nCall me when you want, call me when you need\nCall me in the morning, I'll be on my way`,
    crossLinks: {
      spotify: 'https://open.spotify.com/track/123nasxmontero',
      youtube: 'https://music.youtube.com/watch?v=6zw9v12mG8Y',
    },
  },
  {
    id: 'lib-7',
    title: 'Viva La Vida',
    artist: 'Coldplay',
    album: 'Viva La Vida or Death and All His Friends',
    duration: 242,
    durationFormatted: '04:02',
    releaseYear: '2008',
    genre: 'Alternative Rock',
    platform: 'spotify',
    originalUrl: 'https://open.spotify.com/track/11234455coldplay',
    coverUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
    streamUrl: '/api/stream?title=Coldplay%20-%20Viva%20La%20Vida',
    bitrate: '320 kbps',
    format: 'mp3',
    fileSizeMb: 9.3,
    bpm: 138,
    key: 'Ab Major',
    isDownloaded: true,
    isFavorite: false,
    addedAt: '2026-07-22T08:12:00Z',
    downloadedAt: '2026-07-22T08:12:12Z',
    filePath: 'Music/Coldplay - Viva La Vida.mp3',
    lyrics: `I used to rule the world\nSeas would rise when I gave the word\nNow in the morning I sleep alone\nSweep the streets I used to own`,
    crossLinks: {
      spotify: 'https://open.spotify.com/track/11234455coldplay',
      youtube: 'https://music.youtube.com/watch?v=dvgZkm1xWPE',
    },
  },
  {
    id: 'lib-8',
    title: 'HUMBLE.',
    artist: 'Kendrick Lamar',
    album: 'DAMN.',
    duration: 177,
    durationFormatted: '02:57',
    releaseYear: '2017',
    genre: 'Hip-Hop',
    platform: 'spotify',
    originalUrl: 'https://open.spotify.com/track/humblekendrick',
    coverUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=600&auto=format&fit=crop&q=80',
    streamUrl: '/api/stream?title=Kendrick%20Lamar%20-%20HUMBLE',
    bitrate: '320 kbps',
    format: 'mp3',
    fileSizeMb: 7.1,
    bpm: 150,
    key: 'F# Minor',
    isDownloaded: true,
    isFavorite: true,
    addedAt: '2026-07-21T21:00:00Z',
    downloadedAt: '2026-07-21T21:00:05Z',
    filePath: 'Music/Kendrick Lamar - HUMBLE..mp3',
    lyrics: `Nobody pray for me\nIt's been a day for me\nBe humble, sit down\nBe humble, sit down`,
    crossLinks: {
      spotify: 'https://open.spotify.com/track/humblekendrick',
      soundcloud: 'https://soundcloud.com/kendrick-lamar/humble',
    },
  },
];

export const SAMPLE_PLAYLISTS: import('../types').Playlist[] = [
  {
    id: 'pl-1',
    name: '🔥 Peak Time Dance & Pop (120-130 BPM)',
    description: 'Upbeat club and festival hits perfectly matched for energetic vibes',
    color: 'yellow',
    trackIds: ['lib-2', 'lib-4', 'lib-6', 'lib-7'],
    createdAt: '2026-07-28T10:00:00Z',
    isSmartPlaylist: true,
    targetBpmMin: 120,
    targetBpmMax: 135,
  },
  {
    id: 'pl-2',
    name: '🎧 Melodic Late Night Mix (Camelot 8A/9A)',
    description: 'Harmonically compatible deep tracks with smooth transitions',
    color: 'purple',
    trackIds: ['lib-2', 'lib-3', 'lib-5'],
    createdAt: '2026-07-29T14:30:00Z',
    isSmartPlaylist: true,
    targetKey: '8A',
  },
  {
    id: 'pl-3',
    name: '⭐ Mijn Favoriete Classics',
    description: 'Handmatig samengestelde all-time favorieten',
    color: 'pink',
    trackIds: ['lib-2', 'lib-5', 'lib-8'],
    createdAt: '2026-07-30T18:15:00Z',
    isSmartPlaylist: false,
  },
];

